/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ListShopRouteImport } from './routes/list-shop'
import { Route as IndexRouteImport } from './routes/index'

const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ListShopRoute = ListShopRouteImport.update({
  id: '/list-shop',
  path: '/list-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list-shop': typeof ListShopRoute
  '/parts': typeof PartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list-shop': typeof ListShopRoute
  '/parts': typeof PartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/list-shop': typeof ListShopRoute
  '/parts': typeof PartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list-shop' | '/parts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list-shop' | '/parts'
  id: '__root__' | '/' | '/list-shop' | '/parts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListShopRoute: typeof ListShopRoute
  PartsRoute: typeof PartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-shop': {
      id: '/list-shop'
      path: '/list-shop'
      fullPath: '/list-shop'
      preLoaderRoute: typeof ListShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListShopRoute: ListShopRoute,
  PartsRoute: PartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
